### ISSUE TITLE
Parallel init

### ISSUE THREAD

**Issue by jamesRUS52** [fidum/laravel-dashboard-chart-tile#20]
Hi
How can I init all my charts in dashboard in parallel?
Now I have 7 charts which init one by one
![image](https://user-images.githubusercontent.com/39707635/105331855-008fe200-5be5-11eb-84bb-47cf7709ceaa.png)

**Comment by dmason30** [comment]
As far as I can tell it should be asynchronous. Are you loading different charts or the same charts with different data? If you could provide an example repo that reproduces this but to be honest if anything it will be more of an issue in Chartisan rather than this package. 

This is all the frontend code for this tile:
https://github.com/fidum/laravel-dashboard-chart-tile/blob/master/resources/views/tile.blade.php
